<h1>

  The Rise of Political Influencers—Perspectives on a Trend Towards Meaningful Content
  Magdalena Riedl1*, Carsten Schwemmer1,2, Sandra Ziewiecki3 and Lisa M. Ross3
  1Chair of Political Sociology, Department for Political Science, University of Bamberg, Bamberg, Germany, 2Computational Social Science Department, GESIS—Leibnitz Institute for the Social Sciences, Cologne, Germany, 3Chair of Business Administration, Faculty of Law and Economics, University of Bayreuth, Bayreuth, Germany
  Despite an increasing information overflow in the era of digital communication, influencers manage to draw the attention of their followers with an authentic and casual appearance. Reaching large audiences on social media, they can be considered as digital opinion leaders. In the past, they predominantly appeared as experts for topics like fashion, sports, or gaming and used their status to cooperate with brands for marketing purposes. However, since recently influencers also turn towards more meaningful and political content. In this article, we share our perspective on the rise of political influencers using examples of sustainability and related topics covered on Instagram. By applying a qualitative observational approach, we illustrate how influencers make political communication look easy, while at the same time seamlessly integrating product promotions in their social media feeds. In this context, we discuss positive aspects of political influencers like contributions to education and political engagement, but also negative aspects such as the potential amplification of radical political ideology or conspiracy theories. We conclude by highlighting political influencers as an important research topic for conceptual and empirical studies in the future.
  Keywords: influencer, social media, marketing, opinion leader, political communication, sustainability
  INTRODUCTION
  People spend more and more time on social media to share parts of their daily lives in form of pictures, videos, or text. In addition, the digitization of human communication enables anybody with access to a smartphone to reach huge audiences. These developments illustrate a fundamental shift from one-to-many to many-to-many media communication (Schweiger and Beck 2019). So-called influencers are the pioneers within this development, exploring new possibilities of affecting communication as well as consumption behavior. Their status as opinion leaders as well as their impact on children and teenagers is reflected in a recent study in which nearly a fifth of British children named “influencer” as their dream profession (Skeldon 2019). Influencers often start as ordinary internet users sharing self-produced details of their lives and subsequently become influential by accumulating a large follower base through posting behavior (Abidin 2016, 87). In most cases, they appear as experts for specific topics such as Beauty and Fashion, Fitness, Sports, or Gaming, which are often discussed on social media networks. With increasing professionalization, influencers make use of ads and product placements to monetize the content they produce (Schwemmer and Ziewiecki 2018). By doing so, they often “oscillate between intimacy and publicity, authenticity and commercialization, ingratiation and critical distance” (Enke and
   Frontiers in Communication | www.frontiersin.org 1 December 2021 | Volume 6 | Article 752656
  Riedl et al.
  The Rise of Political Influencers
   Borchers 2019, 255). Besides covering topics such as lifestyle topics, influencers very recently started to integrate political content in their posts. Due to their large online audiences, this topical shift substantially affects content and communication on social media platforms. In this article, we make one of the first attempts to conceptualize the subject of political influencing and consider opinion leadership as a promising theoretical framework. We further shed light on the rise of political influencers using examples drawn from qualitative observations of meaningful trends such as sustainability. In doing so, we not only consider the perspective of users and consumers, but also the perspective of businesses. We close by reflecting upon related challenges as well as opportunities and discuss how future research can help us to learn more about the impact of political influencers.
  INFLUENCERS AS AUTHENTIC OPINION LEADERS
  Over the past years, social media platforms such as YouTube or Instagram developed into leading outlets for commercial purposes. Influencer marketing is considered as a “rapidly growing industry that attempts to promote products or increase brand awareness through content spread by social media users who are considered to be influential” (Carter 2016). Due to their huge online audiences, influencers are often considered as digital opinion leaders (Bause 2021; Soares, Recuero, and Zago 2018; Acharoui et al., 2020; Dubois and Gaffney 2014). Referring to the concept of a two-step flow of communication (Lazarsfeld et al., 1968) opinion leaders are characterized as people who interact with traditional mass media, deal with current issues, reprocess the information and pass them over to other members of their personal networks (Katz 1957, 61). In doing so, they are more active and successful than others in spreading mass media information and influencing opinions within their social networks (Schweiger and Beck 2019). With an increasing overflow of information on social media and digital platforms in general, the concept of opinion leaders and their role as intermediaries for information diffusion is gaining more and more importance. New features of digital platforms related to connectivity and self-communication are further expanding the classical concept of opinion leadership as they allow a more diverse set of actors to exert social influence (Casero-Ripollé, 2020, 171). Besides the importance of influencers for affecting communication and the spread of information online, their actual impact on user attitudes or behavior is difficult to quantify. At the very least influencers are considered to be credible, authentic and trustworthy (Bause 2021; Duckwitz 2019; Schach 2018). Authenticity can be conceptualized as a form of worth (Strand 2014), and influencers manage to create authenticity as an important aspect of their capital mostly by appearing “real” to their followers. Besides their professionalism in staging their daily living and sharing their posts with thousands or millions of people, the casual appearance of the content they produce makes them appear as approachable and
  down-to-earth (Schach 2018, 5; Bulka, Neuhoff, and Siegert 2019; Riedl 2021).
  Platform design is a major factor for the appearance of influencers. For many social media sites such as Instagram or TikTok the presentation of self is the main use case. Winter and Neubaum identify self-presentation goals as one motivational factor for posting opinion expressions in the public sphere (Winter and Neubaum 2016). Both, the focus on self- presentation as a cultural aspect as well as commercialization as a means of monetization are strongly reflected in the design of user interfaces on corresponding platforms (Riedl 2021, 45ff.). At the same time, increasing promotion of products (Schwemmer and Ziewiecki 2018; Mathur, Narayanan, and Chetty 2018) and other factors such as professional production, real-time filters, photo-editing and coverage of mostly casual topics affect platform appearances, but also diminish the authenticity of influencers. According to a survey in Germany, traditional influencers are highly effective when it comes to product promotion: in 2018, every third social media user in Germany discovered a new product through influencers. This share increases to four out of five users for the age group between 16 and 19 years. However, less than two thirds of users mentioned that they would trust content produced by traditional influencers (Wulff et al., 2018). One possible solution for avoiding a reputation of being untrustworthy, superficial, or “fake” is to focus on producing more substantial and politically meaningful content. Since recently, this development can in fact be observed at social media sites, but at the time of writing, only few related scientific studies are available. It is important to note here that a comprehensive literature review is notoriously difficult as “political influencers” are not conceptualized uniformly across studies, for instance, (Casero-Ripollés, 2021). The corresponding operationalization of influencers also includes politicians and journalists. Taking the word literally, influential accounts–such as those from politicians–might be a very good conceptualization of “political influencers” for this study as well as many other research questions. However, it would not necessarily match our definition outlined above, which is more closely related to traditional social media influencers. Besides conceptual work on opinion leadership by Bause (2021), other available studies (Frühbrodt and Floren 2019; Nymoen 2021) appear to focus predominantly on normative and negative aspects of political influencers. By contrast, this article aims to highlight both positive as well as negative aspects of political influencers in conjunction with illustrating new trends in influencer marketing.
  A TREND TOWARDS COMMERCIALIZED POLITICAL CONTENT
  Among other issues such as LGBTQ+ rights or immigration concerns, a topic, which is increasingly covered by influencers to produce meaningful content, is sustainability. Whilst still posting and creating videos that evolve around a certain company or product, some political influencers are now emphasizing topics such as plastic-free living, fair fashion, and conscious consumption behavior (Ziewiecki and Ross 2021). In doing so,
   Frontiers in Communication | www.frontiersin.org 2
  December 2021 | Volume 6 | Article 752656
  
  Riedl et al.
  The Rise of Political Influencers
        FIGURE 1 | Snapshot of greengirlleah Instagram Feed. The Figure shows a screenshot of greengirlleah’s Feed on Instagram including four of her posts. Post number one is a short video displaying a conversation between the two depicted women. The second and third posts contain product promotions for a watch
  as well as for a food company. The fourth post displays a quote of greengirlleah herself (https://www.instagram.com/greengirlleah/, November 26, 2021).
   influencers appeal to their followers by advocating a sustainable and environmentally friendly lifestyle. To provide one example, a 29-year-old American activist who is living a zero-waste life has become an icon for the waste-free movement on Instagram using the profile name trashisfortossers. On her social media profile, one can find sustainable lifestyle tips as well as ad posts for slow fashion. The increasing coverage of sustainability topics cannot only be observed for activists, but also for “traditional” influencers who are now turning towards sustainability and other political topics. Some do so regularly for example by shifting their storytelling from fitness and dieting to self-love and body positivity like louisadellert – a famous German influencer. She started as a fitness influencer sharing pictures of her body, giving training advice, and explaining healthy eating. Now she provides her community with information about feminism, confidentially exposures her orange skin, or draws attention to environmental issues.1 Others share their political opinions only in the context of particular events or occasions, using their reach to highlight current issues which play a critical role in their own lives (Duckwitz 2019, 4). For instance, after the murder of George Floyd2 in the United States, many influencers who were originally not posting political content took position with the hashtag #BLM (“Black Lives Matter”). For a few days,
  1https://www.instagram.com/louisadellert/ 2Hill et al., 2020.
  Instagram was inundated with black tiles, working as a sign of solidarity for People of Color all around the world.
  It is important to note here that a crucial factor for political influencers is not only the coverage of political topics in isolation but rather the way this content is represented. Despite meaningful content, political influencers still focus on a casual, down-to-earth appearance to maintain high credibility among their followers. In that sense, political influencers make politics look easy. To provide an example, Figure 1 includes social media posts of greengirlleah3, an American influencer who dedicates her profile to environmental topics and calls herself a “Climate Optimist”.
  As can be seen in the figure, she enacts herself between political statements and pictures of herself. Post two and three are labelled as paid postings (“#ad”, “#sponsored”) and demonstrate how product promotion is seamlessly integrated into the feed of political influencers. Greengirlleah blends information about the love of animals and spirituality into the promotion of watches and interweaves the advertisement with her informational posts. We consider this integrated mixture of commercialization and political activism as one of the main aspects of political influencing.
  Although systematic empirical evidence is still missing, our qualitative observations suggest avid promotion of products is the norm among political influencers and only few of them do not appear to monetize their content at all. Similar to traditional influencers, political influencers depend upon sponsored posts because they make their living from cooperation and paid partnerships (Ludwig and Dellert, 2021), representing a tension between financial intentions and authentic appearance. For this reason, some political influencers only advertise sustainable objects.
  From a user’s perspective, it is often quite difficult to distinguish between political content and commercialization. To provide another example, Figure 2 depicts trashisfortossers, an influencer who covers DIY zero waste tips and tricks and is followed by over 400.000 people. As can be seen in the figure, she talks about the increasing amount of waste produced through clothing in the United States and the emoji shows her displeasure concerning fast fashion. In the same post, she seamlessly integrates product placement for second-hand e-commerce.
  While influencers actively promote products by well-known companies throughout various platforms and in return receive lucrative incentives in the form of money or complimentary product samples (Gerhards 2019; Hudders, De Jans, and De Veirman 2020), their followers view the ad seamlessly between the authentic narration of entertaining and everyday life details. In addition to simply promoting products of companies, political influencers can make use of their high visibility for other commercial options. While influencers promote own as well as other environmentally friendly products on Instagram, they often also sell a large variety of products through their online shops. For instance, trashisfortossers managed to build herself a sustainability-oriented company called “The Simply Co.” (Van
  3https://www.instagram.com/greengirlleah/.
     Frontiers in Communication | www.frontiersin.org 3
  December 2021 | Volume 6 | Article 752656
  
  Riedl et al.
  The Rise of Political Influencers
        FIGURE 2 | trashisfortossers advertising sustainable e-commerce on her Instagram profile (https://www.instagram.com/p/CN5XMeaF9Yn/, February 08, 2021).
   Schneider 2016), which further demonstrates the potential of influencers for business purposes.
  companies increasingly emphasize the moral dimension within tasks like strategic planning or decision-making procedures (Kuna-Marszałek and Kłysik-Uryszek 2020) At the same time, companies are still trying to be profitable. Concepts like CSR suggest the incorporation of new management models, but ultimately the goal is nevertheless to maximize profits (Ros- Diego and Castelló-Martínez 2011, 3). In that sense, working together with political influencers can fulfill multiple purposes for businesses: adhering to concepts of social responsibility and finding new ways to maximize profits at the same time. For this reason, new marketing strategies are specifically catered towards the storytelling of political influencers.
  Related to the concept of two-step-flow of communication
  referenced above, influencer and followers both are important in
  the diffusion of brand-related information. While they decode
  and distribute the advertised content, followers retrieve, respond
  and share the messages within their own networks (Sundermann
  and Raabe 2019, 284). Taking this into account, influencers help
  companies to disseminate business related posts and videos while
  at the same time reaching large audiences with the ability to target
  specific groups such as younger people (Sursala et al., 2016). This
  form of product promotion not only is considered to be relatively
  inexpensive (Campbell and Farrell 2020), but also authentic and
  trustworthy (Djafarova and Rushworth 2017; Enke and Borchers
  2019). companies tends to improve both competitiveness as well as
  For a better understanding of the role of commercialization, it is helpful to consider political influencing from a business perspective. Advertisement and related marketing concepts are the primary source of monetization for most social media platforms such as Facebook and Instagram. This fact alone is reason enough to consider business perspectives too when studying online communication for such platforms. In addition, with more and more influencers promoting their opinions on certain products or political concepts, it is even more worthwhile to better understand why companies are increasing interested in political influencers for marketing purposes. In recent years, there has been a growing demand to acknowledge the needs of conscious consumers. Companies are increasingly asked to take responsibility for the future and to come up with environment-friendly business concepts (Backhaus-Maul, Kunze, and Nährlich 2018, 236). A related concept is called Corporate Social Responsibility (CSR), which describes the integration of social, labor, and environmental concerns in business practices. Consequentially, some
  the brand image. At the same time, the positive impact of CSR on brand image influences people’s consumption habits (Ros-Diego and Castelló-Martínez 2011, 4; Kuna-Marszałek and Kłysik- Uryszek 2020). From a business perspective, the concept of CSR can therefore bridge the gap between consumerism and political topics such as sustainability, with political influencers becoming a part of a profitable and effective advertising concepts.
  DISCUSSION
  In this article, we introduced political influencers as authentic digital opinion leaders. We highlighted a digital trend towards “meaningful” topics such as sustainability. Similar to traditional influencers, it also became apparent that economic aspects, especially the promotion of products, play an important role for political influencers and companies alike. In that sense, one might cynically think about political influencing as “old wine in new bottles”: old commercialization structures embedded in new
  Apart from ethical reasons, CSR and Marketing are closely bond together since economically responsible behavior from
   Frontiers in Communication | www.frontiersin.org 4
  December 2021 | Volume 6 | Article 752656
  
  Riedl et al.
  The Rise of Political Influencers
   content. At the same time, the rise of political influencers leads to fundamental changes in online communication and the ability of influencers to attract attention is a key factor in that regard. Despite informational overload as constitutive part of social media (Bause 2021, 14), people like trashisfortossers, louisadellert, or greengirlleah are influencing their followers’ opinions with relatively little effort (Skeldon 2019). The challenge of receiving attention online — which influencers are very good at — is a promising topic for future studies. In addition, many open questions concerning the relation between influencers and opinion formation remain. Nevertheless, it is already apparent that the rise of political influencers comes with benefits, but also with potential problems.
  Regarding positive aspects, political influencers may contribute to the education and political information of especially their younger audience. Some studies show that for example certain campaigns can increase students’ interest in scientific content (Donhauser and Beck 2021) and digital food marketing can have a positive impact on children’s food choice (De Jans et al., 2021). Another benefit of influencers turning towards political content is that they can use their reach and popularity to draw attention to or amplify discussions about important topics such as climate change. Furthermore, political influencers make political communication appear easy and approachable, they can potentially stipulate more interest in politics and help to increase political engagement.
  At the same time, increasing product promotion by influencers (Schwemmer and Ziewiecki 2018) highlights the importance of advertising literacy as a concept for developing consumer-related skills (Moschis and Churchill 1978). Children’s advertising literacy does not only include components such as identifying advertising, comprehending persuasive intent and tactics, but also fundamental components of skepticism towards advertising (Hobbs and Paul, 2019). In general, younger consumers have trouble identifying commercial content on social media platforms because they do not fully understand the persuasive character of these new advertising formats (Hudders et al., 2016; van Reijmersdal and van Dam 2020). Regarding the perspective of companies, we discussed how political influencers are well aligned with corporate responsibility frameworks, which ultimately does not affect the actual purpose of influencer marketing: getting people to buy products. Some companies might simply exploit the conscientious impressions of political influencers instead of actively endorsing green-living responsibility (Förster, 2020). Another important aspect to consider is that political influencers represent and spread opinions across the entire political spectrum. In some cases, this leads to the dissemination of extremist or anti-democratic viewpoints as well as conspiracy theories. For instance, a German political influencer is spreading dangerous conspiracy theories
  regarding the COVID-19 pandemic to over 100,000 followers on his channel SchrangTV (Niehr 2021).
  Ultimately, our perspective on the rise of political influencers is still limited by a lack of systematic empirical evidence. Future research could work with both qualitative (see for instance Abdulmajeed and El Ibiary 2020) as well as quantitative empirical designs to examine the role political influencers play in public discourse especially through their social media accounts Future research should also analyze the impact of influencers on the dissemination of information on digital platforms as well as the effects of political influencers on opinion formation, interest in politics as well as political engagement. Political candidates as well as parties started to utilize influencers for reaching potential voters. In the United States election 2020, presidential candidate Michael Bloomberg engaged in paid partnerships on social media (Lorenz 2020). In Germany, the political party CSU invited influencers to political events and since recently also creates influencer-like social media posts on platforms such as TikTok. It remains to be seen to what extent political influencers will be able to affect not only digital communication and economic consumption, but also political behavior and electoral outcomes in the future.
  DATA AVAILABILITY STATEMENT
  The original contributions presented in the study are included in the article/Supplementary Material, further inquiries can be directed to the corresponding author.
  ETHICS STATEMENT
  Written informed consent was not obtained from the individual(s) for the publication of any potentially identifiable images or data included in this article.
  AUTHOR CONTRIBUTIONS
  MR and CS took the lead in writing the initial draft, with contributions from all authors. All authors provided critical feedback and helped shape the research and the final manuscript.
  FUNDING
  This paper originated from the project “Political Influencers in Germany”, generously funded by the Bavarian Institute of digital Transformation (BIDT).
</h1>