<h1>Journalism and Social Media Audiences
  Tahrir Square quietly celebrated an anniversary on January 2016—it had been five years since the popular uprisings that toppled Egypt’s Mubarak government and brought a global audience to major political rebellions occurring across the Middle East. However, this anniversary was not at all reminiscent of the highly mediated public protests of 2011. Instead, a crackdown on any form of public dissent, including raids on the homes of activists and even outlawing street vendors in Tahrir Square, indicated the new Egyptian government’s attitude towards this public anniversary. While major news organisations published some commemorative fea- ture articles and Al Jazeera (Arab Spring Protesters 2016) reported that smaller groups of anti-government protesters had formed on the day of the anniversary, media reportage was nowhere near the global phenom- enon that had created the ‘Arab Spring’ five years previously.
  The so-called Arab Spring began in Tunisia in 2010, as a public response to the self-immolation of street vendor Mohamed Bouaziz, which brought large-scale protests about government corruption to the country. The ferocity of the protests resulted in the resignation of President Zine El Abidine Ben Ali and sparked popular uprisings in Libya, Yemen, Syria, Egypt and other countries. It was the protests in Egypt that inspired much of the global media’s attention, because well- organised and media-savvy activist groups were also working to publicise and document the protests on social media. Both academic and media commentators drew attention to the seemingly collaborative relationship protesters had with international journalists to report upon daily events
  © The Author(s) 2017 47 D. Bossio, Journalism and Social Media,
  DOI 10.1007/978-3-319-65472-0_3
  Bossio, D. (2017). Journalism and social media : Practitioners, organisations and institutions. Springer International Publishing AG. Created from washington on 2022-04-23 18:53:10.
   Copyright © 2017. Springer International Publishing AG. All rights reserved.
  48 D. BOSSIO
  and social issues in Egypt more broadly. Some of the more hyperbolic analysis described a ‘social media revolution’, where traditional media audiences gained some control of the news agenda by sharing thousands of eyewitness accounts, videos, tweets and Facebook posts on social media platforms, rather than through traditional media (Lister and Smith 2011; Lotan et al. 2011).
  Five years has shown both the oversimplification of a ‘social media revolution’ and, more importantly, the inherent complexity of the rela- tionship between news organisations, journalists and their audiences. While subsequent analysis of the Arab Spring has shown evidence of journalist and citizen collaborations for reportage (Bossio 2014), as well as innovative use of citizen-focussed reportage (Bruns et al. 2012), the reality of social media-enabled interactions between journalists and citizens was rather more limited. Similarly, the Egyptian, Tunisian and Libyan people have faced difficulties affecting social change subsequent to the fervour of revolution—and away from the glare of international media attention.
  While the previous chapter focussed on journalistic practice in social media environments, this chapter explores the traditional ‘recipients’ of journalism—the news media audience. In particular, the apparent empowerment of audiences on social media and the dominance of their preferences in the production and consumption of news (Anderson 2011, p. 557). The traditional news audience has always been active and dynamic—news audiences have always commented, interpreted and shared news. Letters to the editor in local newspapers and com- munity notice boards are traditional reminders of the active nature of audiences. However, the emergence of digital, online and social media- enabled environments has changed the traditionally ‘one-way’ commu- nication relationship between journalists and their audiences, making it possible for audiences to ‘talk back’ by commenting, sharing and even making their own media content (Bruns 2007). Similarly, the tradi- tional conception of audiences as a unified mass has been overtaken by distributed networks, niche groupings and issue-oriented audiences on social media (Heinrich 2011). This has led to a conceptual change in the representation of news audiences, from ‘passive consumers of news that needed to be given “the information they needed” by professional journalists’, to an empowered force for the co-creation and distribu- tion of news (Anderson 2011, p. 564). Academic and industry research has also taken an ‘audience turn’ (Lee and Chyi 2014), analysing
  Bossio, D. (2017). Journalism and social media : Practitioners, organisations and institutions. Springer International Publishing AG. Created from washington on 2022-04-23 18:53:10.
  Copyright © 2017. Springer International Publishing AG. All rights reserved.
  
  3 JOURNALISM AND SOCIAL MEDIA AUDIENCES 49
  the different ways the audience has become part of the journalistic pro- cess. Some research has shown that increased audience interaction via social media has provided new reportage opportunities for journalists (Lee et al. 2014). Others have suggested that these interactions may be use- ful during coverage of specific events or issues, but tensions emerge in transitioning these interactions to an overall professional or organisational approach to audience engagement (Hedman and Djerf-Pierre 2013).
  While much of this research has focussed on how a more engaged audience has created changes in the production and distribution of news, this chapter will focus more broadly on the ways in which public dia- logue has changed. Public dialogue is defined as deliberate, participatory engagement with an event or issue by a diverse mix of public participants in order to share knowledge and experiences. Importantly, this engage- ment does not require uniformity of opinion, nor a shared outcome, but merely a connection through participation in the topic. This is important within online and social media spaces, where traditional social constructs, such as the nation, break down and ‘new knowledge communities’ emerge based on voluntary, temporary, and strategic groupings (Jenkins and Ito 2015). Members of these communities shift as their interests develop, or they belong to multiple knowledge communities, each being sustained by the common need for production and exchange of particu- lar kinds of public dialogue. Bruns and Burgess (2011) define these con- nections on social media as ‘ad hoc publics’, where short-term networks or groups for discussion might appear around particular events, posts or content and some users might become influential through their engage- ment with these topics or events. Ad hoc publics are not static, and may change or become part of established online communities over time. Within these social media spaces, news becomes a distributed conversa- tion in which a number of individuals are responding simultaneously to events as a kind of ‘ambient journalism’ (Hermida 2011). Social media interactions between users can thus be seen as an aggregated form of journalistic content, experienced as a constant ambient presence in social media spaces, but becoming more explicit when major news breaks. Shaw et al. (2013, p. 23) suggest this results in a ‘public and collective’ expression of public dialogue about particular news events, either with- out the need for input from professional journalists, or in connection with traditional news organisations.
  The ideal of this participatory communication is the creation of online publics that allow for dynamic civic engagement with social and cultural
  Bossio, D. (2017). Journalism and social media : Practitioners, organisations and institutions. Springer International Publishing AG. Created from washington on 2022-04-23 18:53:10.
  Copyright © 2017. Springer International Publishing AG. All rights reserved.
  
  50 D. BOSSIO
  issues (Jenkins 2006). This ideal has often been framed by the repre- sentation of unified groups working collaboratively within networks to debate and to affect change (Livingstone 2005). However, the reality of the emergence of this participatory online culture has been much more complex and heterogeneous. In particular, traditional norms of pub- lic dialogue framed by professional ideologies, and governmental and legal norms have become sites of contestation in online and social media spaces, as audiences resist or recreate the power structures that framed public engagement, sometimes in deliberately ‘uncivil’ ways, such as trolling or satirical hoaxes. In the context of journalism, online and social media have changed the nature of dialogue between journalists and audi- ences, creating new spaces for the audience to critique, re-present, dis- miss, or even completely ignore the journalist.
  This chapter argues that this has changed public dialogue, especially the roles of participants, and the ‘rules of engagement’ in participatory forms of social media communication. Crawford (2009, p. 528) sug- gests that online spaces create interconnections through ‘access to the details of someone’s everyday life, as prosaic as they often are, which contributes to the sense of “ambient intimacy” in social media’. This constant access to ambient intimacy, as well as the dominance of affec- tive content based on personal opinion and experience, and, finally, the centrality of the user in the construction of ad hoc publics engaged with issues and events of interest creates public spaces and communi- ties with very different cultures, politics and rules of civil engagement. McCosker (2014) argues that ‘a truly pluralistic participatory experi- ence includes not just being affected by new forms and flows of net- worked media content and communication, but also the power to affect with new forms of reciprocal capacity to act out and even “act up”’. For many users, emotional, satirical and even combative forms of engage- ment with news events are simply a way of participating in information flows as part of a broader sense of social media communication cul- ture—participation and contribution to social and cultural life through the particular affordances of social media. However, this communica- tion culture differs exponentially from the tightly governed, structured forms of communication created by traditional norms of professional journalism.
  This chapter uses a case study of the Egyptian Arab Spring to chart these changes, proceeding firstly by illustrating how the definition of the news audience has changed, and secondly by contextualising the new
  Bossio, D. (2017). Journalism and social media : Practitioners, organisations and institutions. Springer International Publishing AG. Created from washington on 2022-04-23 18:53:10.
  Copyright © 2017. Springer International Publishing AG. All rights reserved.
  
  3 JOURNALISM AND SOCIAL MEDIA AUDIENCES 51
  audience–journalist relationship through the norms of professional prac- tice established in the previous chapter. The changes that have occurred in this relationship since the introduction of social media forms of com- munication are also discussed, such as new audience-led forms of jour- nalism. Finally, using examples from reportage of the Arab Spring sets the context for understanding some of the opportunities and challenges that social media-led interactions with traditional audiences can bring to both journalistic practice and public dialogue and engagement more broadly.
  how ‘audiences’ have changed—a Problem of definition
  Much of the international reportage about the Arab Spring protests throughout 2011 and 2012 reflected the hopeful determination so proudly displayed by protesters in Egypt’s Tahrir Square. Despite days of social upheaval and violence, many professional journalists reported that the activists’ demands for ‘bread, freedom and social justice’ would surely be met (Yassin-kassab et al. 2016). Hosni Mubarak’s resignation from his presidency almost 20 days into the protests seemed to confirm the push towards social reform in the country. Five years later, much of that hopeful determination has turned to despair. News reports docu- menting the rise and fall of President Mohammad Morsi, the outlawing of the Muslim Brotherhood, rigged elections and violent clashes between protesters and police have marred the optimism created by the Arab Spring. By 2014, the entire Egyptian government had resigned, paving the way for former army chief Abdel Fattah el-Sisi to become president. More recent news reports have detailed the jailing and disappearance of activists who came to prominence during the Arab Spring, as well as the banning of public protests and sidelining of opposition parties. As the now-jailed Egyptian activist Alaa Abd El-Fattah suggests, Egypt’s Arab Spring had gone from a narrative of change to ‘a dangerous cocktail of nationalist, nativist, collectivist and post-colonialist language appropri- ated by both sides of the conflict and used to spin convoluted conspir- acy theories and spread paranoia’ (Yassin-kassab et al. 2016). Indeed, El-Fattah suggests the loss of ‘hope’ came with the loss of the ‘narra- tive of revolution’, a narrative that was once facilitated in part by thou- sands of highly educated and media-savvy young activists sharing media
  Bossio, D. (2017). Journalism and social media : Practitioners, organisations and institutions. Springer International Publishing AG. Created from washington on 2022-04-23 18:53:10.
  Copyright © 2017. Springer International Publishing AG. All rights reserved.
  
  52 D. BOSSIO
  content, which was curated and distributed by professional journalists to worldwide audiences. Engagement of global audiences through social media and professional journalism helped to fuel this narrative, but as the fervour died down and eyeballs and hashtags turned elsewhere, the pub- lic dialogue between witnesses, reporters and audiences became much more difficult for everyday Egyptians to facilitate.
  Perhaps this change in the narrative of the Arab Spring reflects the heterogeneity of various publics in social media environments. Indeed, one of the problems with describing the changes occurring between journalists and audiences on social media in the context of the Arab Spring was defining who the audience actually was. The heterogeneity of publics in social media environments means that the nature of public dia- logue is also fragmented between various interests and groups. Defining the audience is not a new problem in media or journalism studies; in fact, it has been the subject of much theoretical discussion, especially since conception of the ‘mediatisation’ of cultural and social life through the pervasive influence of broadcast and online technologies (Hjarvard 2008). For example, Ang’s (1991) work to understand industrial defini- tion of the televisual audience illustrates the complexity of the audience’s composition and actions in media spheres. Ang (1991, p. 13) refers to the actual world of audiences, not as distinct groups, but as a ‘shorthand’ for ‘infinite, contradictory, dispersed and dynamic’ experiences of tele- vision enacted in people’s everyday lives. Indeed, the audience itself is a construction, socially and institutionally produced for industrial, eco- nomic and cultural aspirations (Ang 1991, p. 3). The difference between this audience construction and the reality of audience activity is the dyna- mism of everyday engagement with media; ‘a heterogeneous range of informal activities, uses, interpretations, pleasures, disappointments, con- flicts, struggles, compromises’ (Ang 1991, p. 2). But the more institu- tional view of the audience dismisses the heterogeneity of the audience in favour of the representation of a unified group, which can be easily quan- tified for the purposes of creating content. This creates a power dynamic that is exploited by media producers and their organisational structures, which results in subjugating the audience (Ang 1991, p. 23). However, these previously stable, industrialised conceptions of audience have been disrupted somewhat by the social actions and interactions afforded by social media technologies.
  Newer theorisations of the ‘quantified’ audience refer to web and social media analytics to illustrate how the relationship between
  Bossio, D. (2017). Journalism and social media : Practitioners, organisations and institutions. Springer International Publishing AG. Created from washington on 2022-04-23 18:53:10.
  Copyright © 2017. Springer International Publishing AG. All rights reserved.
  
  3 JOURNALISM AND SOCIAL MEDIA AUDIENCES 53
  journalists and audiences is being disrupted by conceptions of audiences as paradoxically productive and quantifiable. Anderson (2011, p. 551) argues that traditional conceptions of audiences as a ‘quantifiable and largely consumptive aggregate’ have been challenged by newer under- standings of the generative qualities of online and social media audiences. Yet, as news organisations transition their practices to more audience- engaged newsrooms, there remains a tension between the increasingly prominent and widespread techniques of audience measurement, the characterisation of an active audience, and the journalist’s own profes- sional ideologies (Anderson 2011, p. 552). The use of online and social media has thus shifted the organisational understanding of the use of the audience—from a mass that needs to be fed news, to a creative force whose exact needs and preferences can be analysed to frame the news agenda. This has led to the increased organisational use of technologies that allows measurement and analysis of audiences, as well as manage- ment strategies that emphasise the subsequent audience metrics in the creation of the news agenda (Anderson 2011, p. 555). While the positive and negative impacts of social media analytics will be discussed further in Chap. 5, the use of these analytics has also impacted on the relationship between journalists and audiences.
  While many journalists acknowledge the increasingly intercon- nected relationship between news producers and audiences, it has not always been easy to give up authority over the representation of news. For example, Hille and Bakker’s (2014) research shows that journalists do not actually engage with audiences after they have published their news stories, with much of the user commentary creating conversation amongst users rather than being monitored by journalists themselves. While journalists may still resist some forms of audience participation in the news, they do acknowledge the importance of audience consumption preferences in setting the news agenda: ‘Whereas reporters were once surprised by reader feedback, it seems that they now expect reader feed- back, even if they do not like it, agree with it, or see it as enhancing their ultimate journalistic product’ (Anderson 2011, p. 558). Furthermore, the relevance of the increased use of audience metrics is symptomatic of increasingly collaborative and quantified relations between journalists and audiences.
  The organisational understanding of the social media audience has at times mimicked the industrial prioritisation of quantifiable engagements with the audience—seen in the strategic use of analytics to measure the
  Bossio, D. (2017). Journalism and social media : Practitioners, organisations and institutions. Springer International Publishing AG. Created from washington on 2022-04-23 18:53:10.
  Copyright © 2017. Springer International Publishing AG. All rights reserved.
  
  54 D. BOSSIO
  preferences of audiences. Livingstone (2005, p. 18), suggests that quan- tification limits the actual dynamism of the audience: ‘the effect of media on their audience is seen to reposition what was or might be or should be, a public (knowing, thinking, influential) as a mere crowd (watching, sharing and emoting) or mass of consumers (driven by tastes, preferences and motivations)’. This means that only certain groups or activities are seen as being for ‘the public’, while the ‘audience’ is merely an industrial tool, not considered as important to the functioning of society. Instead, Livingstone (2005, p. 18) suggests that conceptions of publics speak for the will of the people, while audiences are spoken to, by much larger organisational structures. This is not to say that individual users or social media content do not also have commercial or strategic interests. Rather, it is the form of communication on social media that has changed and the roles and rules of engagement within them. Conceptions of social media publics prioritise the individual expression of users and personal interconnections based on ‘public and collective’ expression of public affect about particular news event (Shaw et al. 2013, p. 23). Journalists, just like any other user, can become influential in these networks, but public dialogue about news on social media is no longer reliant on input from professional journalists, or connection with traditional news organisations.
  the arab sPring and social media audiences
  The Egyptian Arab Spring is an example of the way in which journal- ists’ autonomy and social authority was replaced in some instances by the collaborative efforts of interested ad hoc publics on social media. While analysis of mainstream journalistic practice during the Arab Spring in Egypt has shown that mainstream news was still predominantly rep- resented through traditional reportage of professional correspondents (Bossio and Bebawi 2013), many international journalists flying into Egypt found that their practices were disrupted by intentional band- width throttling by governmental agencies, as well as military-enforced curfews. However, some journalists connected with Egyptian activists who were aware of the benefits of raising awareness of the protests for international media audiences. This resulted in a mix of professional and ‘non-professional’ modes of news media production interacting in order to source, confirm and distribute information to both local and global audiences (Bossio and Bebawi 2013). Thus, journalists were curating
  Bossio, D. (2017). Journalism and social media : Practitioners, organisations and institutions. Springer International Publishing AG. Created from washington on 2022-04-23 18:53:10.
  Copyright © 2017. Springer International Publishing AG. All rights reserved.
  
  3 JOURNALISM AND SOCIAL MEDIA AUDIENCES 55
  Twitter, YouTube and Facebook posts from activists, which supplemented their own coverage of the uprisings, especially during state crackdowns on journalists in Egypt.
  There were also instances of mainstream journalists on social media encouraging local people to phone or email to keep journalists updated during communications blackouts. For example, Al Jazeera English (AJE) was targeted as a ‘dissident’ channel in Egypt, and during the ini- tial days of protest, Egypt’s Information Ministry revoked AJE’s media accreditation (Bossio 2014). Egyptian authorities shut down AJE’s Cairo bureau, and shut off satellite access to the channel (Egypt shuts down 2011). AJE was forced to find another satellite service outside Egypt and relied on social media to put together the news. Indeed, AJE was probably the most prominent of the international media organisations to prioritise both the use of social media and collaborative reportage with protesters. On the other hand, media-savvy Egyptian activists integrated their own rallying cries with hashtags; slogans for revolution were posted on social media platforms, alongside their own eyewitness reports and links to international reportage. In this environment, public dialogue shifted, incorporating much more collaborative and iterative notions of news production, as well as more dynamic information flows (Heinrich 2011, p. 62). Both the audience and the journalists took part in this collaborative mode of news production, with each participant in pub- lic dialogue becoming what Bruns (2006, p. 275) describes as a ‘hybrid user-producer’.
  The increasingly blurred boundaries between production and recep- tion of news has led some to question the need for a ‘professional’ journalist (Berkman and Shumway 2003). Downing (2001, p. ix), for example, has argued for alternative journalistic practice as ‘radi- cal’, ‘grassroots’ or ‘community’ media, though these definitions have been forwarded more as a structure of information dissemination and practice not purely focussed on journalism (Bossio and Bebawi 2013). ‘Citizen’ journalism has also become a popular term to describe the link between alternative news practice to forms of citizenship practice and empowerment (Rodriguez 2001, p. 20). These alternative types of journalism have a political, economic and institutional impera- tive to produce news ‘outside mainstream media institutions and net- works’, working with amateurs ‘who typically have little or no training or professional qualifications as journalists’ (Atton and Hamilton, p. 1). Others (see Brodin 2011; Livingstone 1999) have highlighted the need
  Bossio, D. (2017). Journalism and social media : Practitioners, organisations and institutions. Springer International Publishing AG. Created from washington on 2022-04-23 18:53:10.
  Copyright © 2017. Springer International Publishing AG. All rights reserved.
  
  56 D. BOSSIO
  for trained or professional journalists to work with amateurs to verify information and encourage adherence to particular institutional and ethical guidelines.
  These debates concerning the demarcation of journalism against other types of news creation suggest the complex disruptions that have con- tributed to the definition of journalism in social media environments, where the edges between public dialogue and journalistic practice are somewhat blurred. During the protests in Egypt, for example, people were involved in what we might call journalistic practices: eyewitness reportage and analysis of event, as well as video, audio and social media updates. Some were paid as journalists for Egyptian media outlets, others considered themselves journalists though were not paid, some were col- laborating with news organisations and others were defining what they were doing simply as important information dissemination in a time of crisis (Bossio 2014). Some were also reporting from outside Egypt itself, using online resources to ‘cover’ the protest. Some were not Egyptian citizens but were participating in the reportage of information through other online networks. However, only some of those people identified what they were doing as ‘journalism’ or media production. It is the com- plexity of these interactions that encapsulates the dynamism of social media cultures of communication and the mix of commercial, political and social motivations that influence them.
  new audience concePtions for social media interactions
  The seeming collapse of boundaries between media users, produc- ers, audiences and activists suggests the complexity of communica- tive relations during the Arab Spring. Whereas protesters embraced the information dissemination possibilities of new technologies—and were also personally invested in the outcome of the protests—journal- ists were reporting on use of new digital technologies as both insiders (users of social media) and outsiders (observing the use of social media by others). While some academic and media commentators were sug- gesting that social media use during the protests was an indication of a true ‘revolution of the people’, others were decrying a ‘social media revolution’ (Lotan et al. 2011 ; Gladwell 2010). As described above, the complexity lies in the understanding of the audience and resistance
  Bossio, D. (2017). Journalism and social media : Practitioners, organisations and institutions. Springer International Publishing AG. Created from washington on 2022-04-23 18:53:10.
  Copyright © 2017. Springer International Publishing AG. All rights reserved.
  
  3 JOURNALISM AND SOCIAL MEDIA AUDIENCES 57
  to the performance of the role traditionally ascribed to the audience in this space. The variability of both the production and consumption of social media by journalists, protestors and different audiences indicates the changing nature of public dialogue in social media environments. In the social media space, increasingly fragmented ad hoc audiences with various interests ‘speak’ at the same time and for different purposes, but are nonetheless ‘defined’ or interconnected through their inter- est in particular events or phenomena. Similarly, both commercial and social definitions of the audience sit alongside each other in social media spaces. While public dialogue may be the motivation for interactions on social media during the Arab Spring, activists and journalists were well aware of the economies of clicks and likes that would ensure this dia- logue was heard and re-distributed. What has changed then, is the domi- nance of the ‘public’ in the sourcing, creation and distribution of news and the constant renegotiation of roles and rules within social media communication.
  Baym and boyd (2012, p. 320) have suggested social media ‘public- ness’ requires new structures of interaction and new skills to understand them. This is made more dynamic as users negotiate ‘blurred boundaries, multi-layered audiences, individual attributes, the specifics of the systems they use, and the contexts of their use’. What is new about these inter- actions on social media is the global acceptance of users’ control over the application of the affordances of social media for their own objectives and public interactions (Baym and boyd 2012, p. 321). Thus, the social media audience is different from traditional audiences because it takes for granted the ‘multiple and diverse kinds of publics, counterpublics, and other emergent social arrangements...The sometimes quasi-public and other times entirely public nature of social media’. The public nature of interaction and the control of publics over use of tools within particu- lar contexts ‘makes visible processes that have always been at play, while warping them in ways that call for new literacies and strategies’ (Baym and boyd 2012, p. 322). In the context of journalism, the audience for commercial, promotional and entertainment functions of news runs par- allel to the political and social functions of news—the different kinds of engagements with these functions occur with different types of dialogues within various online publics and creating different opportunities and tensions—all at the same time. Thus, the change that social media envi- ronments bring to audience and journalist communicative relations is the
  Bossio, D. (2017). Journalism and social media : Practitioners, organisations and institutions. Springer International Publishing AG. Created from washington on 2022-04-23 18:53:10.
  Copyright © 2017. Springer International Publishing AG. All rights reserved.
  
  58 D. BOSSIO
  visibility of the inherent complexity of the social, cultural and political engagement and framing of news.
  Russell (2016) argues that a discussion of these different relations between journalists and online publics is inherently useful to the insti- tution of journalism. She uses the description, popularised by Beckett (2011), ‘networked journalism’ to define practice as diffuse and net- worked. In public dialogue conducted in social media environments, the journalist still adheres to professional norms and behaviours, but the authority of the journalist within this dialogue is decentralized and dif- fuse. Instead, a networked journalist acts as just one node that collects, processes, and distributes (and re-distributes) information. Within an organisational structure, the journalist still acts as a ‘professional’, with professional norms and public interest principles motivating production of news for audiences that seek to engage with a news organisation’s content, but their practice is assumed to occur simultaneously with other forms of news information gathering and dissemination. Similarly, it can be assumed that this professional practice is linked with, and sometimes even dependent on, collaboration with sources, as well as audience feed- back in online environments. Thus, journalists and their various online audiences can no longer be conceptualised as separate, but as interlinked nodes in a network of news and information. A networked journalist working within various ‘publics’ thus contributes to new professional norms by acting as a generator, witness, and interpreter of professional journalism (Hermida 2011), re-interpreting and sharing news as part of a relationship with a number of interested publics. In this environment of journalistic production, Hamilton (2016) suggests a new kind of public audience or ‘citizen witnessing’, as a hybridisation of the individual with the social, the mainstream with the alternative. Rather than usurping the power of news outlets, this active production of news is a produc- tive addition of diversity, correction and iterative processes to traditional news production (Hamilton 2016). Of course, these relations are based primarily on sharing.
  As the traditional demarcations between journalist and audience collapse within social media environments, a culture of sharing encap- sulates the complex, networked interactions that occur in the com- munication and dissemination of news on social media. The concept of online and social media sharing has its beginnings in computing, where sharing was popularised as file- or data-sharing (see John 2012). But social media platforms encourage many different forms of sharing,
  Bossio, D. (2017). Journalism and social media : Practitioners, organisations and institutions. Springer International Publishing AG. Created from washington on 2022-04-23 18:53:10.
  Copyright © 2017. Springer International Publishing AG. All rights reserved.
  
  3 JOURNALISM AND SOCIAL MEDIA AUDIENCES 59
  for many different interests. Traditional online sharing is about the communication and distribution of digital content, such as images or links. But now, sharing is much broader; sharing encapsulates the repre- sentation of life through sharing of your location, your opinion through a like, or feeling through a status update or emoticon. We generally understand sharing on social media platforms to be the consistent, daily sharing of links and videos of small bits of personal and professional news and comments. John (2012, p. 176) suggests that online shar- ing seems overwhelmingly positive because of the pairing with notions of strong social relations within a unified public. However, the invita- tion to share on social media has also been exploited by commercial and political interests that profit from individual and collective emotional capital. For example, in the context of journalism, we often think of the promotional sharing practices of journalists and organisations that bring ‘eyeballs’ to particular media content. However, sharing also speaks to the institutional values we place on journalism as a way to activate the democratic potential of various publics. A journalist shares news for two outcomes: firstly, the more traditional distribution of news as an infor- mational resource, and, more recently, for the collaborative work that extends from these shared resources (Cammaerts and Couldry 2016, p. 329). Thus, sharing is a collaborative as well as a dialogic media practice that has become integral to journalism in social media environments.
  Understanding and conceptualising sharing in a social media context is a way to encapsulate the social ideals of journalism practice without creating the power dynamic that maintains journalistic authority over the production and dissemination of news. While some sharing on social media platforms will undoubtedly maintain the promotional practices of professional journalists trying to find larger audiences for their content, the inclusion of various audiences in the production and dissemination of news will also allow sharing associated with a broader public dia- logue. Of course, sharing within emerging news practice is constrained by several issues, especially the reproduction of existing models of jour- nalistic practice and power structures within individual professional and organisational use of social media. There is no doubt that both jour- nalists and their audiences are constrained by the social, governmental, technological, organisational and institutional structures that limit the ways in which they are able to interact and share on social media. For example, Bossio and Sacco (2016) suggest journalists have been asked by their organisations to refrain from posting breaking news on social
  Bossio, D. (2017). Journalism and social media : Practitioners, organisations and institutions. Springer International Publishing AG. Created from washington on 2022-04-23 18:53:10.
  Copyright © 2017. Springer International Publishing AG. All rights reserved.
  
  60 D. BOSSIO
  media before cross-media promotion of the story has occurred. Thus, commercial and promotional frameworks placed upon public dialogue may hinder the potential for social media collaboration and sharing. Indeed, Cammaerts and Couldry (2016, p. 337) also lament that some of these new practices of sharing are instrumental because they reinforce individualistic capitalist value systems of individual sharing, rather than public dialogue. Journalists attempting to emulate the success of social media ‘influencers’, for example, might find it difficult to maintain both the institutional boundaries of professional journalism and the promo- tional imperative of social media branding (Hanusch and Bruns 2017). Thus, understanding of sharing must acknowledge the unfair distribution of possibilities to participate; uneven distribution and access to technolo- gies, mediation of expression through the corporate structures of tech- nology companies, and government-imposed restrictions that seek to exclude all but the already privileged from public dialogue.
  Similarly, conceptions of public dialogue on social media must tem- per excessive emphasis on participatory and political potential of the plat- forms. Indeed, subsequent analysis of the Arab Spring protests found that social media use during the Arab Spring tended to be overstated (Bruns et al. 2013). Further analysis of hashtags used during the Arab Spring showed that they were only a communicative tool for the organi- sation of protests in the initial days of the Arab Spring and then were more likely to be used by ‘elite’ Arab and English-speaking users as an awareness-raising and news engagement tool (Bruns et al. 2013). On the other hand, Egyptian activists and bloggers consistently conveyed infor- mation to their readers using social media, re-tweeting coverage from the mainstream press, and occasionally criticizing the coverage, but in the main using it as a source of credible information. The media that was meant to inform protesters and activists was simultaneously convey- ing news and awareness in the international community through the dis- tribution of ‘alternative’ or ‘citizen’ online and social media reportage. Protesters were often aware of this process, directing tweets to ensure that major news organisations were covering parts of the crisis where activists had an interest in amplifying coverage.
  Both media producers and audiences are constrained by the commer- cial, political and social limits placed on the use of social media. Within social media environments, the use of different forms of literacies, lan- guages and cultural norms to describe news events and issues creates both possibilities and tensions in the communicative relations between
  Bossio, D. (2017). Journalism and social media : Practitioners, organisations and institutions. Springer International Publishing AG. Created from washington on 2022-04-23 18:53:10.
  Copyright © 2017. Springer International Publishing AG. All rights reserved.
  
  3 JOURNALISM AND SOCIAL MEDIA AUDIENCES 61
  journalists and audiences. This does not necessarily always have negative outcomes—social media is a space that makes visible the complexity and diversity of voices in the public sphere and provides for interaction and collaboration on certain issues, though not on others. In social media environments, audiences share, comment on, critique, interpret, and add content and witness statements, or even ignore news content alto- gether. Use of social media is innovative at times and, at others, limited by different social, organisational and governmental contexts. Thus, as Livingstone (2005, p. 31) suggests, a news audience is ‘generally neither so passive and accepting as traditionally supposed by those who deni- grate them, nor generally so organised and effective as to meet the high standards of those defining public participation’. Active participation of audiences in media production and dissemination does not mean that audiences have ‘ultimate power’ in communicative relations, or even on social media. Indeed, Fiske and Hancock (2016) suggest the audience’s power is not necessarily to change media production or institutional structures, but simply to negotiate the effects of those structures within the context of their interest and need. Perhaps the biggest difference in social media environments is that audiences interact within a number of different publics or groups, with new forms of dialogue and participation required for each. Using social media as the framework for communi- cation, audiences are also producers, witnesses, participators and publics at the same time and, thus, the traditional contexts for—and controls over—public dialogue collapse in these spaces.
  While evidence of sustained collaboration between journalists and audiences within social media environments is currently somewhat rare, the development of these smaller, ‘rolling’ moments of sharing is still constitutive of changes in the institutional conception of journalism. Indeed, the interactions between various publics and journalists, espe- cially concerning crisis events, shows that journalists have been able to curate a myriad of stories for particular audiences through the interac- tion with particular networks (Bossio and Bebawi 2013). While Bennett and Segerberg (2013, p. 214) suggest we still do not know what ‘a suc- cessful transition [to social media] looks like’, this does not mean that this transition is not occurring—the dynamic and heterogeneous use of social media both by journalists and audiences will ensure that we cannot predict what it will look like, nor the ‘correctness’ of how it will come about. As these changes occur, we are reminded by Livingstone (2005, p. 32) that changes in the way audiences and journalists interact may not
  Bossio, D. (2017). Journalism and social media : Practitioners, organisations and institutions. Springer International Publishing AG. Created from washington on 2022-04-23 18:53:10.
  Copyright © 2017. Springer International Publishing AG. All rights reserved.
  
  62 D. BOSSIO
  be the ‘ideal’, but social media interactions will occur in rather the same constrained and limited ways as other ‘new’ media have allowed: ‘That, after all, is the point: it is precisely such context-dependent yet under- determined, plural and hybrid identities, understandings, practices and relationships that must and do shape people’s engagement with others, in private and in public.’
  conclusion
  The Arab Spring protests were the result of repressive social and gov- ernmental policies that inflicted hardship, especially on young peo- ple, in the countries affected. Perhaps global audiences would not have been so aware of this plight without the collaborative efforts of local activists, journalists and everyday Egyptians documenting their strug- gle online and on social media. Local organisation of protests and action was undoubtedly reliant on local networks of activists, but the global reach of these protests, fuelled by mainstream news reportage, was also assisted by social media like Facebook and Twitter, especially when report- age was increasingly difficult due to communications blackouts. The Arab Spring protests are one of the first examples of clear collaboration between journalists and various publics not only to create media content, but to ensure its wide dissemination through processes of sharing such as ‘hashtagging’, personal appeals for information and use of witness state- ments and amateur media content as part of reportage.
  The Arab Spring protests illustrates that the conception of the audi- ence as a traditionally stable and unified epistemological construct is no longer adequate to describe either the relationship between jour- nalists and audiences, nor the specific roles within it. This chapter has instead argued that social media cultures of communication have enabled new formations of public dialogue and new roles for both journalists and their audiences. The Arab Spring is an example of the complexity of these relations; journalists, media producers and various audiences all negotiated communication around particular vested interests. These interests included the social importance of exchanging particular kinds of news and information, the organisational need to inform particular audi- ence demographics in an ethical and professional way, and even the need to develop online relationships with publics according to cultural norms of particular social media platforms. The complex interactions between journalists and publics illustrates the heterogeneous nature of social
  Bossio, D. (2017). Journalism and social media : Practitioners, organisations and institutions. Springer International Publishing AG. Created from washington on 2022-04-23 18:53:10.
  Copyright © 2017. Springer International Publishing AG. All rights reserved.
  
  3 JOURNALISM AND SOCIAL MEDIA AUDIENCES 63
  media interactions and the need to conceptualise the new forms of dia- logue that occur there, especially in the news and information context.
  In the next two chapters, the focus shifts from the individual practi- tioners and creators of journalistic content to the organisational frame- works that produce mainstream news. This part of the book takes an organisational perspective on the introduction of social media to the newsroom. This approach considers the newsroom relationships, policies and procedures that impact both the ways in which individual practition- ers do their job, and the overall production and dissemination of news. Chapter 4, ‘Social Media and the Newsroom: New Relationships, New Policies, New Practices’, argues that while there is much variation in the ways that newsrooms have attempted to integrate social media use into the newsroom, and how journalists themselves manage those policies and procedures, it is in fact the relationship between journalistic, edito- rial and management staff that determines whether integration of social media in the newsroom is perceived as successful.
  references
  Anderson, C. W. (2011). Between creative and quantified audiences: Web met- rics and changing patterns of newswork in local US newsrooms. Journalism, 12(5), 550–566.
  Ang, I. (1991). Desperately seeking the audience. London: Routledge.
  Arab Spring Protesters Defy Crackdown. (2016, January 26). Al Jazeera. Retrieved from http://www.aljazeera.com/news/2016/01/arab-spring-
  anniversary-protesters-defy-crackdown-160125061915269.html.
  Atton, C., & Hamilton, J. (2008). Alternative journalism. London: Sage.
  Baym, N., & boyd, d. (2012). Socially mediated publicness: An introduction.
  Journal of Broadcasting & Electronic Media, 56(3), 320–329.
  Beckett, C. (2011). SuperMedia: Saving journalism so it can save the world.
  Chichester: Wiley.
  Bennett, W. L., & Segerberg, A. (2013). The logic of connective action: Digital
  media and the personalization of contentious politics. Cambridge: Cambridge
  University Press.
  Berkman, R., & Shumway, C. (2003). Digital dilemmas: Ethical issues for online
  media professionals. Iowa City: Iowa State Press.
  Bossio, D. (2014). Journalism during the Arab Spring: Interactions and chal-
  lenges. In S. Bebawi & D. Bossio (Eds.), Social media and the politics of reportage: The Arab Spring. London: Palgrave Macmillan.
  Bossio, D. (2017). Journalism and social media : Practitioners, organisations and institutions. Springer International Publishing AG. Created from washington on 2022-04-23 18:53:10.
  Copyright © 2017. Springer International Publishing AG. All rights reserved.
  
  64 D. BOSSIO
  Bossio, D., & Bebawi, S (2013). War of Worlds? Alternative and mainstream jour- nalistic practices in coverage of the ‘Arab Spring’ protests. In J. E. Hayes, k. Battles, & W. Hilton-Morrow (Eds.), War of the words to social media: Mediated communication in times of crisis (pp. 189–211). New York: Peter Lang.
  Bossio, D., & Sacco, V. (2016). Don’t tweet this! How journalists and media organisations negotiate tensions emerging from the implementation of social media policy in newsrooms. Digital Journalism, 5(2), 177–193.
  Brodin, S. (2011, October 21). In the aftermath of the Arab Spring revolutions, journalists ask, who is a journalist? European Journalism Centre Magazine. Retrieved from http://www.ejc.net/magazine.
  Bruns, A. (2006). Towards produsage: Futures for user-led content production. In F. Sudweeks, H. Hrachovec, & C. Ess. (Eds.), Proceedings of Cultural Attitudes towards Communication and Technology (pp. 275–284). Tartu, Estonia.
  Bruns, A. (2007). Produsage: Towards a Broader Framework for User-Led Content Creation. Paper presented at the Creativity & Cognition conference, Washington, DC. Retrieved from https://www.eprints.qut.edu.au/6623/1 /6623.pdf.
  Bruns, A., & Burgess, J. (2011). The use of Twitter hashtags in the formation of ad hoc publics. In Proceedings of the 6th European Consortium for Political Research (ECPR) General Conference 2011. University of Iceland, Reykjavik. Retrieved from https://www.eprints.qut.edu.au/46515/1/The_Use_of_ Twitter_Hashtags_in_the_Formation_of_Ad_Hoc_Publics_%28final%29.pdf.
  Bruns, A., Highfield, T., & Lind, R. A. (2012). Blogs, Twitter, and breaking news: The produsage of citizen journalism. Produsing Theory in a Digital World: The Intersection of Audiences and Production in Contemporary Theory, 80(2012), 15–32.
  Bruns, A., Highfield, T., & Burgess, J. (2013). The Arab Spring and social media audiences: English and Arabic Twitter users and their networks. American Behavioral Scientist, 57(7), 871–898.
  Cammaerts, B., & Couldry, N. (2016). Digital journalism as practice. In T. Witschge, C. Anderson, & D. Domingo (Eds.), The SAGE Handbook of Digital Journalism (pp. 326–340). London: Sage.
  Crawford, k. (2009). Following you: Disciplines of listening in social media. Continuum, 23(4), 525–535.
  Downing, J. (2001). Radical Media: Rebellious Communication and Social move- ments. London: Sage Publications.
  Egypt shuts down Al Jazeera bureau. (2011, January 30). Al Jazeera. Retrieved from- http://www.aljazeera.com/news/middleeast/2011/01/201113085252994161. html.
  Fiske, J., & Hancock, B. H. (2016). Power plays power works (2nd ed.). New York: Routledge.
  Bossio, D. (2017). Journalism and social media : Practitioners, organisations and institutions. Springer International Publishing AG. Created from washington on 2022-04-23 18:53:10.
  Copyright © 2017. Springer International Publishing AG. All rights reserved.
  
  3 JOURNALISM AND SOCIAL MEDIA AUDIENCES 65
  Gladwell, M. (2010, October 4). Small Change: Why the revolution will not be tweeted. The New Yorker. Retrieved from http://www.newyorker.com/ magazine/2010/10/04/small-change-malcolm-gladwell.
  Hamilton, J. (2016). Hybrid news practices. In T. Witschge, C. Anderson, & D. Domingo (Eds.), The SAGE Handbook of digital Journalism (Vol. 55, pp. 164–178). London: Sage.
  Hanusch, F., & Bruns, A. (2017). Journalistic Branding on Twitter. Digital Journalism, 5(1). Retrieved from http://www.tandfonline.com/doi/full/10 .1080/21670811.2016.1152161.
  Hedman, U., & Djerf-Pierre, M. (2013). The social journalist. Digital. Journalism, 1(3), 368–385.
  Heinrich, A. (2011). Network Journalism: Journalistic Practice in Interactive Spheres. Hoboken, NY: Routledge.
  Hermida, A. (2011). Fluid spaces, fluid journalism: Lessons in participatory journalism. In Jane B. Singer, D. Domingo, A. Heinonen, A. Hermida, S. Paulussen, T. Quandt, et al. (Eds.), Participatory journalism: Guarding open gates at online newspapers (pp. 177–191). Malden, MA: Wiley-Blackwell.
  Hille, S., & Bakker, P. (2014). Engaging the social news user: Comments on news sites and Facebook. Journalism Practice, 8(5), 563–572.
  Hjarvard, S. (2008). The Mediatisation of society: A Theory of the Media as Agents of Social and Cultural Change.Nordicom Review, 29(2), 105–134.
  Jenkins, H. (2006). Convergence culture: Where old and new media collide. New York: NYU press.
  Jenkins, H., & Ito, M. (2015). Participatory culture in a networked era: A con- versation on youth, learning, commerce, and politics. Chichester: Wiley.
  John, N. A. (2012). Sharing and Web 2.0: The emergence of a keyword. New Media & Society, 15(2), 167–182.
  Lee, A. M., & Chyi, H. I. (2014). When Newsworthy is Not Noteworthy: Examining the value of news from the audience’s perspective. Journalism Studies, 15(6), 807–820.
  Lee, A. M., Lewis, S. C., & Powers, M. (2014). Audience clicks and news place- ment: A study of time-lagged influence in online journalism. Communication Research, 41(4), 505–530.
  Lister, T., & Smith, E. (2011, January 27). Social media @the frontline in Egypt. CNN. Retrieved from http://edition.cnn.com/2011/WORLD/ africa/01/27/egypt.protests.social.media/.
  Livingstone, S. (1999). New media, new audiences? New Media and Society, 1(1), 59–66.
  Livingstone, S. (2005). Audiences and publics: When cultural engagement mat- ters for the public sphere. Changing Media, Changing Europe Series. Bristol: Intellect.
  Lotan, G., Graeff, E., Ananny, M., Gaffney, D., & Pearce, I. (2011). The Arab Spring: The revolutions were tweeted: Information flows during the 2011
  Bossio, D. (2017). Journalism and social media : Practitioners, organisations and institutions. Springer International Publishing AG. Created from washington on 2022-04-23 18:53:10.
  Copyright © 2017. Springer International Publishing AG. All rights reserved.
  
  66 D. BOSSIO
  Tunisian and Egyptian revolutions. International journal of communication,
  5. Retrieved from http://www.ijoc.org/index.php/ijoc/article/view/1246 McCosker, A. (2014). Trolling as provocation: YouTube’s agonistic pub- lics. Convergence: The International Journal of Research into New Media
  Technologies, 20(2), 201–217.
  Rodriguez, C. (2001). Fissures in the mediascape: An international study of citi-
  zens’ media. Cresskill, NJ: Hampton Press.
  Russell, A. (2016). Networked journalism. In T. Witschge, C. Anderson, & D.
  Domingo (Eds.), The SAGE Handbook of digital Journalism (pp. 149–163).
  London: Sage.
  Shaw, F., Burgess, J., Crawford, k., & Bruns, A. (2013). Sharing news, making
  sense, saying thanks. Australian Journal of Communication, 40(1), 23–39. Yassin-kassab, R., Abd El Fattah, A., Soueif, A., Barghouti, M., Lalami, L., Shehadeh, R., et al. (2016, January 23). I was terribly wrong—writers look back on the Arab Spring Five years on. The Guardian. Retrieved from: https://www.theguardian.
  com/books/2016/jan/23/arab-spring-five-years-on-writers-look-back.</h1>